### ISSUE TITLE
描述错误，代码错误

### ISSUE THREAD

**Issue by zhiziqixingdeng** [NIHAOAWA/nihaoawa.github.io#1]
首先，不是选择其中一个部署，必须html，css，js都部署才行，要不然咋访问???
还有，你发现了吗，我们的html根本连接不上css和js，请马上修改，要不然可能根本用不了

**Comment by NIHAOAWA** [comment]
废话，这都不是一套的你咋一起部署？？？剩下两套我说你自己写，搞得我哭笑不得

**Comment by zhiziqixingdeng** [comment]
> 
据我所知，您根本不会css和js吧，而且，就算不是一套，也得在自述文件里说说吧，一直都弄得我想骂你

**Comment by zhiziqixingdeng** [comment]
> 废话，这都不是一套的你咋一起部署？？？剩下两套我说你自己写，搞得我哭笑不得

说不过就删除评论，傻逼

**Comment by zhiziqixingdeng** [comment]
笑死，你的里面没有说明这个js是干什么用的，别人怎么写剩下两套?

**Comment by zhiziqixingdeng** [comment]
笑死，你的里面没有说明这个js是干什么用的，别人怎么写剩下两套?

**Comment by zhiziqixingdeng** [comment]
笑死，你的里面没有说明这个js是干什么用的，别人怎么写剩下两套?

**Comment by zhiziqixingdeng** [comment]
笑死，你的里面没有说明这个js是干什么用的，别人怎么写剩下两套?
