### ISSUE TITLE
本仓库一个或多个文件涉嫌非法复制

### ISSUE THREAD

**Issue by MrZhang365** [NIHAOAWA/nihaoawa.github.io#2]
请注意，本仓库的一个或多个文件涉嫌非法复制（未遵守许可证要求），请及时处理，否则后果自负。

受影响的文件：
README.md

被非法复制的文件：
https://github.com/ZhangChat-Dev-Group/ZhangChat/blob/main/README.md

被非法复制的文件许可证：
Apache-2.0

详细内容：
> ## 安装与部署
> ### 先决条件
> …
> ### 部署
> …

（格式涉嫌非法复制）

**Comment by NIHAOAWA** [comment]
我改一下

**Comment by NIHAOAWA** [comment]
改完了

**Comment by MrZhang365** [comment]
OK
